---
- name: Ensure PIP config directory exist and has proper permissions.
  file:
    dest: "{{ pipconfig_dir | expanduser }}"
    mode: "{{ pipconfig_dir_mode }}"
    state: directory

- name: Copy PIP config
  copy:
    dest: "{{ pipconfig_dir | expanduser + '/' + pipconfig_file }}"
    mode: "{{ pipconfig_file_mode }}"
    src: "templates/pip.conf"

- name: Install PIP config
  template:
    dest: "{{ pipconfig_dir | expanduser + '/' + pipconfig_file }}"
    mode: "{{ pipconfig_file_mode }}"
    src: "pip.conf"


# vim: et:sw=2:syntax=yaml:ts=2:
